name: API Specification Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  IMAGE_NAME: nutsfoundation/hashicorp-vault-proxy
  TEST_TAG: test

jobs:

  build_and_test:
    name: Build and test API

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.TEST_TAG }}

    - name: Setup
      working-directory: ./test
      run: |
        docker compose up --wait

    - name: Run API tests
      working-directory: ./test
      run: |
        docker run --network=vault-proxy-test --volume=${PWD}/postman-testsuite.json:/opt/postman-testsuite.json:ro postman/newman run /opt/postman-testsuite.json --env-var="api_address=http://proxy:8210"
