---
name: 'Build Docker images'

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version params
        id: version
        shell: bash
        run: echo "git_version=$(git name-rev --tags --name-only $(git rev-parse HEAD))" >> $GITHUB_OUTPUT

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true

      - name: Print version params
        run: |
          echo "Version: ${{ steps.version.outputs.git_version }}"
          echo "Latest tag: ${{ steps.get-latest-tag.outputs.tag }}"
          echo "This tag: ${{ github.ref }}"

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: nutsfoundation/hashicorp-vault-proxy
          tags: |
            # generate 'main' tag for the main branch
            type=ref,event=branch,enable={{is_default_branch}},prefix=
            # generate v5.2.1 tag
            type=semver,pattern={{version}}
          flavor: |
            latest=${{ steps.version.outputs.git_version == steps.get-latest-tag.outputs.tag }}
            prefix=v,onlatest=false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
