name: Docker Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST_TAG: nuts-foundation/hashicorp-vault-proxy:test

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v4
      with:
        images: nutsfoundation/hashicorp-vault-proxy
        tags: |
          # generate 'master' tag for the master branch
          type=ref,event=branch,enable={{is_default_branch}}
          # generate v5.2.1 tag
          type=semver,pattern=v{{version}}
          # generate v5 tag
          type=semver,pattern=v{{major}}
        flavor: |
            latest=auto
            
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and export to Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: ${{ env.TEST_TAG }}
    
    - name: setup vault
      run: |
        docker run -d --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=root' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200' --name=vault vault
        docker exec -e VAULT_TOKEN=root vault vault secrets enable -version=1 -address=http://localhost:8200 kv

    - name: setup proxy
      run: |
        docker run nuts-foundation/hashicorp-vault-proxy:${{ env.TEST_TAG }} -e 'VAULT_ADDR=http://vault:8200' -e 'VAULT_TOKEN=root' --name=proxy

    - name: run e2e test
      run: |
        docker run --volume=${PWD}/test/postman-testsuite.json:/opt/postman-testsuite.json:ro postman/newman run /opt/postman-testsuite.json --env-var="api_address=http://proxy:8210"
    
